module.exports = [

    "🎮 What game have you been playing the most lately?",
    "🎮 What's the first game you ever played?",
    "🎮 What's your favorite gaming memory?",
    "🎮 What game deserves a sequel?",
    "🎮 What's the most underrated game you've played?",
    "🎮 What game could you replay forever?",
    "🎮 What's your favorite multiplayer game?",
    "🎮 What's your favorite single-player game?",
    "🎮 Which game has the best soundtrack?",
    "🎮 Which game world would you live in?",

    "🎵 What song has been stuck in your head recently?",
    "🎵 What's your favorite song right now?",
    "🎵 Which artist would you love to see live?",
    "🎵 What's your comfort song?",
    "🎵 What song never gets old?",
    "🎵 What's your favorite music genre?",
    "🎵 Which artist is underrated?",
    "🎵 What's the best concert you've attended?",
    "🎵 Which album has no skips?",
    "🎵 What's a song everyone should hear once?",

    "🍕 What food could you eat forever and never get tired of?",
    "🍔 What's your favorite fast-food restaurant?",
    "🍟 What's your favorite snack?",
    "🍩 Sweet or savory?",
    "🍫 What's your favorite dessert?",
    "🥤 What's your favorite drink?",
    "🍜 What's a food everyone should try once?",
    "🍍 Pineapple on pizza: yes or no?",
    "🍳 What's your go-to breakfast?",
    "🌮 What's the best takeaway food?",

    "🎬 Best movie or show you've watched recently?",
    "📺 Favorite comfort show?",
    "🎬 What's the funniest movie you've seen?",
    "🎬 What's your all-time favorite movie?",
    "📺 What show should everyone watch?",
    "🎬 What's the most overrated movie?",
    "📺 What are you currently watching?",
    "🎬 Favorite movie quote?",
    "📺 Favorite animated show?",
    "🎬 What's a movie you'll never watch again?",

    "💬 What's one thing you're proud of this week?",
    "💬 What's something you're looking forward to?",
    "💬 What's your dream job?",
    "💬 What's a skill you wish you had?",
    "💬 What's something you've learned recently?",
    "💬 What's one goal you're working toward?",
    "💬 What motivates you?",
    "💬 What's your favorite hobby?",
    "💬 What's something you're grateful for today?",
    "💬 What's your biggest achievement this year?",

    "🤔 Would you rather fly or teleport?",
    "🤔 Would you rather travel to the past or future?",
    "🤔 Would you rather be famous or rich?",
    "🤔 Would you rather explore space or the deep ocean?",
    "🤔 Would you rather pause time or rewind time?",
    "🤔 Would you rather never sleep or never eat?",
    "🤔 Would you rather live underwater or on the moon?",
    "🤔 Would you rather know every language or play every instrument?",
    "🤔 Would you rather always be early or always be late?",
    "🤔 Would you rather have unlimited money or unlimited free time?",

    "📚 What's your favorite school subject?",
    "📚 What's the most useful thing you've learned?",
    "📚 What subject should schools teach more?",
    "📚 What's the hardest subject you've studied?",
    "📚 Online learning or in-person learning?",
    "💼 What's your dream workplace?",
    "💼 What's the best job you've had?",
    "💼 What's your biggest productivity trick?",
    "📚 What skill should everyone learn?",
    "💼 If money wasn't a factor, what would you do every day?",

    "🐶 If animals could talk, which would be the rudest?",
    "👽 If aliens landed tomorrow, what's the first thing you'd ask?",
    "🦸 What superpower would be most useful in daily life?",
    "🏰 What fictional world would you live in?",
    "🚀 If you could visit any planet, which one?",
    "🎭 Which fictional character would be the worst roommate?",
    "🎁 What's the best gift you've ever received?",
    "🎉 What's your perfect weekend?",
    "🎪 What's the weirdest dream you've ever had?",
    "🚗 What's your dream car?",

    "🌱 What's the best advice you've ever received?",
    "🌱 What does success mean to you?",
    "🌱 What's one thing you'd change about the world?",
    "🌱 What inspires you?",
    "🌱 What's a lesson you've learned the hard way?",
    "🌱 What's something society should value more?",
    "🌱 What makes a good friend?",
    "🌱 What's something you hope to accomplish one day?",
    "🌱 What's a challenge that made you stronger?",
    "🌱 If you could give everyone one piece of advice, what would it be?",

    "😴 What's the worst sleep schedule you've ever had?",
    "📱 What app do you use the most every day?",
    "🔥 What's a hot take you'll defend forever?",
    "🧠 What random fact do you know for no reason?",
    "🏝️ If you could instantly travel anywhere right now, where?",
    "🌙 Are you more productive at night or during the day?",
    "💀 What's the dumbest injury you've ever gotten?",
    "🎧 Favorite artist right now?",
    "📸 What's your favorite photo you've ever taken?",
    "⭐ What's something on your bucket list?"
];